# Generated by Django 5.0.6 on 2024-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='como_hacerlo',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descrip_ejercicio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descrip_programa',
            field=models.CharField(max_length=250),
        ),
    ]
