# Generated by Django 5.0.6 on 2024-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ejercicio_como_hacerlo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='como_hacerlo',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='peso',
            field=models.CharField(max_length=100),
        ),
    ]
