# Generated by Django 5.0.6 on 2024-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ejercicio_como_hacerlo_alter_ejercicio_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='nombre_plato',
            field=models.CharField(max_length=100),
        ),
    ]
