# Generated by Django 5.0.6 on 2024-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comida_nombre_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='image',
            field=models.TextField(default='assets/image/goal_1.png'),
            preserve_default=False,
        ),
    ]
