# Generated by Django 5.0.6 on 2024-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuarios_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
