# Generated by Django 5.0.6 on 2024-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='exercises',
            field=models.TextField(default='1 hora'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='image',
            field=models.TextField(default='assets/images/what_1.png'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='time',
            field=models.TextField(default='3 ejercicios'),
        ),
    ]
