# Generated by Django 5.0.6 on 2024-05-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_entrenamiento_exercises_entrenamiento_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='image',
            field=models.CharField(default='assets/images/img_1.png', max_length=100),
        ),
    ]
