# Generated by Django 5.0.6 on 2024-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_findeat_todaymeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaymeal',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
