# Generated by Django 5.0.6 on 2024-05-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ingredientes_nutrition_paso'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoySleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
    ]
